-- up to date as of May 28, 2026

create table public.ai_overview (
  id bigint generated by default as identity not null,
  security_id bigint not null,
  model_ver text not null,
  prompt_ver text not null,
  headline text not null,
  content jsonb not null,
  generated_at timestamp with time zone not null default now(),
  flagged boolean null default false,
  constraint ai_overview_pkey primary key (id, generated_at),
  constraint ai_overview_security_id_fkey foreign KEY (security_id) references securities (security_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;


create table public.event_history (
  security_id bigint not null,
  event_id bigint generated by default as identity not null,
  event_date date not null,
  title text not null,
  description text null,
  event_type text null,
  scope text null,
  source text null,
  constraint event_history_pkey primary key (security_id, event_id, event_date),
  constraint event_history_natural_unique unique (security_id, event_date, event_type),
  constraint event_history_security_id_fkey foreign KEY (security_id) references securities (security_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;


create table public.macro_calendar (
  date date not null,
  event_type text not null,
  days_to_event integer null,
  event_date date not null,
  constraint macro_calendar_pkey primary key (date, event_type)
) TABLESPACE pg_default;


create table public.model_runs (
  id bigint generated always as identity not null,
  run_date date not null,
  model_version text not null,
  spec_hash text null,
  n_tickers integer null,
  horizons integer[] null,
  notes text null,
  created_at timestamp with time zone null default now(),
  constraint model_runs_pkey primary key (id)
) TABLESPACE pg_default;


create table public.options_chain (
  id bigint generated by default as identity not null,
  security_id bigint not null,
  snapshot_date date not null,
  expiry date not null,
  strike numeric(10, 2) not null,
  option_type character(1) not null,
  bid numeric(8, 2) null,
  ask numeric(8, 2) null,
  mid numeric(8, 2) null,
  last numeric(8, 2) null,
  volume integer null,
  open_interest integer null,
  iv double precision null,
  delta double precision null,
  constraint options_chain_pkey primary key (id),
  constraint options_chain_snapshot_unique unique (
    security_id,
    snapshot_date,
    expiry,
    option_type,
    strike
  ),
  constraint options_chain_security_id_fkey foreign KEY (security_id) references securities (security_id) on update CASCADE on delete CASCADE,
  constraint options_chain_option_type_check check (
    (
      option_type = any (array['C'::bpchar, 'P'::bpchar])
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_opt_security_snapshot on public.options_chain using btree (security_id, snapshot_date) TABLESPACE pg_default;

create index IF not exists idx_opt_security_expiry on public.options_chain using btree (security_id, snapshot_date, expiry) TABLESPACE pg_default;

create unique INDEX IF not exists contract on public.options_chain using btree (
  security_id,
  snapshot_date,
  expiry,
  option_type,
  strike
) TABLESPACE pg_default;


create table public.prices_history (
  security_id bigint not null,
  date date not null,
  open numeric null,
  close numeric null,
  high numeric null,
  low numeric null,
  adj_close numeric null,
  volume bigint null,
  constraint prices_history_pkey primary key (security_id, date),
  constraint prices_history_security_id_fkey foreign KEY (security_id) references securities (security_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_prices_security_date on public.prices_history using btree (security_id, date desc) TABLESPACE pg_default;


CREATE  TABLE public.securities (
  security_id bigint NOT NULL,
  ticker text NOT NULL DEFAULT ''::text,
  gics_sector text NULL DEFAULT ''::text,
  gics_industry text NULL DEFAULT ''::text,
  sector_etf text NULL DEFAULT ''::text,
  active boolean NULL DEFAULT true,
  min_history_date date NULL,
  last_model_run timestamp without time zone NULL DEFAULT now(),
  excluded_reason text NULL,
  company_name text NULL,
  gics_subindustry text NULL,
  CONSTRAINT securities_pkey PRIMARY KEY (security_id)
) TABLESPACE pg_default;


create table public.shap_snapshot (
  security_id bigint not null,
  retrain_date date not null,
  horizon integer not null,
  snapshot_date date not null,
  base_value double precision null,
  predicted_value double precision null,
  feature_data jsonb not null,
  constraint shap_snapshot_pkey primary key (security_id, retrain_date, horizon),
  constraint shap_snapshot_security_id_fkey foreign KEY (security_id) references securities (security_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_shap_recent on public.shap_snapshot using btree (security_id, snapshot_date desc, horizon) TABLESPACE pg_default;


create table public.volatility_history (
  security_id bigint not null,
  date date not null,
  rv double precision null,
  iv_atm double precision null,
  vrp_wedge double precision null,
  pfv_21 double precision null,
  pfv_63 double precision null,
  pfv_126 double precision null,
  pfv_cal_21 double precision null,
  pfv_cal_63 double precision null,
  pfv_cal_126 double precision null,
  pfv_q15_21 double precision null,
  pfv_q15_63 double precision null,
  pfv_q15_126 double precision null,
  fwd_premium_21d double precision null,
  fwd_premium_63d double precision null,
  fwd_premium_126d double precision null,
  fwd_premium_21_to_63d double precision null,
  fwd_premium_63_to_126d double precision null,
  ewma_vol double precision null,
  iv_atm_30d double precision null,
  iv_atm_60d double precision null,
  iv_atm_91d double precision null,
  iv_atm_182d double precision null,
  vrp_wedge_ewma_21d double precision null,
  next_earnings_date date null,
  days_to_earnings integer null,
  next_dividend_date date null,
  days_to_dividend integer null,
  model_run_id bigint null,
  shap_h21_top10 jsonb null,
  shap_h63_top10 jsonb null,
  shap_h126_top10 jsonb null,
  constraint volatility_history_pkey primary key (security_id, date),
  constraint volatility_history_model_run_id_fkey foreign KEY (model_run_id) references model_runs (id) not VALID,
  constraint volatility_history_security_id_fkey foreign KEY (security_id) references securities (security_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_vol_security_date on public.volatility_history using btree (security_id, date desc) TABLESPACE pg_default;