-- Initial schema. Mirrors the hosted database (supabase/database_SQL_defs.sql) so local
-- `supabase db reset` produces the same structure as production.
-- Tables are ordered by FK dependency (database_SQL_defs.sql lists them alphabetically,
-- which is not execution-safe).

CREATE TABLE securities (
  security_id     bigint NOT NULL,
  ticker          text NOT NULL DEFAULT ''::text,
  gics_sector     text DEFAULT ''::text,
  gics_industry   text DEFAULT ''::text,
  sector_etf      text DEFAULT ''::text,
  active          boolean DEFAULT true,
  min_history_date date,
  last_model_run  timestamp without time zone DEFAULT now(),
  excluded_reason text,
  company_name    text,
  gics_subindustry text,
  CONSTRAINT securities_pkey PRIMARY KEY (security_id)
);

CREATE TABLE model_runs (
  id            bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  run_date      date NOT NULL,
  model_version text NOT NULL,
  spec_hash     text,
  n_tickers     integer,
  horizons      integer[],
  notes         text,
  created_at    timestamptz DEFAULT now(),
  CONSTRAINT model_runs_pkey PRIMARY KEY (id)
);

CREATE TABLE volatility_history (
  security_id            bigint NOT NULL,
  date                   date NOT NULL,
  rv                     double precision,
  iv_atm                 double precision,
  vrp_wedge              double precision,
  pfv_21                 double precision,
  pfv_63                 double precision,
  pfv_126                double precision,
  pfv_cal_21             double precision,
  pfv_cal_63             double precision,
  pfv_cal_126            double precision,
  pfv_q15_21             double precision,
  pfv_q15_63             double precision,
  pfv_q15_126            double precision,
  fwd_premium_21d        double precision,
  fwd_premium_63d        double precision,
  fwd_premium_126d       double precision,
  fwd_premium_21_to_63d  double precision,
  fwd_premium_63_to_126d double precision,
  ewma_vol               double precision,
  iv_atm_30d             double precision,
  iv_atm_60d             double precision,
  iv_atm_91d             double precision,
  iv_atm_182d            double precision,
  vrp_wedge_ewma_21d     double precision,
  next_earnings_date     date,
  days_to_earnings       integer,
  next_dividend_date     date,
  days_to_dividend       integer,
  model_run_id           bigint,
  shap_h21_top10         jsonb,
  shap_h63_top10         jsonb,
  shap_h126_top10        jsonb,
  CONSTRAINT volatility_history_pkey PRIMARY KEY (security_id, date),
  CONSTRAINT volatility_history_security_id_fkey FOREIGN KEY (security_id)
    REFERENCES securities (security_id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT volatility_history_model_run_id_fkey FOREIGN KEY (model_run_id)
    REFERENCES model_runs (id)
);

CREATE INDEX idx_vol_security_date ON volatility_history (security_id, date DESC);

CREATE TABLE prices_history (
  security_id bigint NOT NULL,
  date        date NOT NULL,
  open        numeric,
  close       numeric,
  high        numeric,
  low         numeric,
  adj_close   numeric,
  volume      bigint,
  CONSTRAINT prices_history_pkey PRIMARY KEY (security_id, date),
  CONSTRAINT prices_history_security_id_fkey FOREIGN KEY (security_id)
    REFERENCES securities (security_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX idx_prices_security_date ON prices_history (security_id, date DESC);

CREATE TABLE options_chain (
  id            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  security_id   bigint NOT NULL,
  snapshot_date date NOT NULL,
  expiry        date NOT NULL,
  strike        numeric(10,2) NOT NULL,
  option_type   character(1) NOT NULL,
  bid           numeric(8,2),
  ask           numeric(8,2),
  mid           numeric(8,2),
  last          numeric(8,2),
  volume        integer,
  open_interest integer,
  iv            double precision,
  delta         double precision,
  CONSTRAINT options_chain_pkey PRIMARY KEY (id),
  CONSTRAINT options_chain_snapshot_unique UNIQUE (security_id, snapshot_date, expiry, option_type, strike),
  CONSTRAINT options_chain_security_id_fkey FOREIGN KEY (security_id)
    REFERENCES securities (security_id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT options_chain_option_type_check CHECK (option_type = ANY (ARRAY['C'::bpchar, 'P'::bpchar]))
);

CREATE INDEX idx_opt_security_snapshot ON options_chain (security_id, snapshot_date);
CREATE INDEX idx_opt_security_expiry   ON options_chain (security_id, snapshot_date, expiry);
-- Mirrors the hosted DB, which has both this index and the options_chain_snapshot_unique constraint over the same columns.
CREATE UNIQUE INDEX contract ON options_chain (security_id, snapshot_date, expiry, option_type, strike);

CREATE TABLE ai_overview (
  id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  security_id  bigint NOT NULL,
  model_ver    text NOT NULL,
  prompt_ver   text NOT NULL,
  headline     text NOT NULL,
  content      jsonb NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now(),
  flagged      boolean DEFAULT false,
  CONSTRAINT ai_overview_pkey PRIMARY KEY (id, generated_at),
  CONSTRAINT ai_overview_security_id_fkey FOREIGN KEY (security_id)
    REFERENCES securities (security_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE shap_snapshot (
  security_id     bigint NOT NULL,
  retrain_date    date NOT NULL,
  horizon         integer NOT NULL,
  snapshot_date   date NOT NULL,
  base_value      double precision,
  predicted_value double precision,
  feature_data    jsonb NOT NULL,
  CONSTRAINT shap_snapshot_pkey PRIMARY KEY (security_id, retrain_date, horizon),
  CONSTRAINT shap_snapshot_security_id_fkey FOREIGN KEY (security_id)
    REFERENCES securities (security_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX idx_shap_recent ON shap_snapshot (security_id, snapshot_date DESC, horizon);

-- Per-security events. Market-wide events (CPI/FOMC/NFP) live in macro_calendar.
CREATE TABLE event_history (
  security_id bigint NOT NULL,
  event_id    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  event_date  date NOT NULL,
  title       text NOT NULL,
  description text,
  event_type  text,
  scope       text,
  source      text,
  CONSTRAINT event_history_pkey PRIMARY KEY (security_id, event_id, event_date),
  CONSTRAINT event_history_natural_unique UNIQUE (security_id, event_date, event_type),
  CONSTRAINT event_history_security_id_fkey FOREIGN KEY (security_id)
    REFERENCES securities (security_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE macro_calendar (
  date          date NOT NULL,
  event_type    text NOT NULL,
  days_to_event integer,
  event_date    date NOT NULL,
  CONSTRAINT macro_calendar_pkey PRIMARY KEY (date, event_type)
);

CREATE FUNCTION get_distribution(
    p_security_id    INT,
    p_metric         TEXT,    -- 'rv' | 'iv_atm_30d' | 'vrp_wedge' | 'pfv_cal_21'
    p_lookback_days  INT DEFAULT 1260
) RETURNS TABLE (
    scope               TEXT,    -- 'stock' | 'sector' | 'market'
    bin_low             DOUBLE PRECISION,
    bin_high            DOUBLE PRECISION,
    count               INT,
    current_value       DOUBLE PRECISION,
    current_percentile  DOUBLE PRECISION
) AS $$
BEGIN
    -- Placeholder function - to be implemented with actual distribution logic
    RETURN QUERY SELECT 'stock'::TEXT, 0::DOUBLE PRECISION, 0::DOUBLE PRECISION, 0::INT, 0::DOUBLE PRECISION, 0::DOUBLE PRECISION WHERE FALSE;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE user_dashboard (
  user_id UUID NOT NULL REFERENCES auth.identities(id) PRIMARY KEY,
  watchlist JSONB NOT NULL DEFAULT '[]'::jsonb
);


-- Enable Row Level Security on all tables

-- 1. Securities table
ALTER TABLE securities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to securities"
  ON securities FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Restrict write access to authenticated users"
  ON securities FOR INSERT
  TO authenticated
  WITH CHECK (false);

CREATE POLICY "Restrict update access to authenticated users"
  ON securities FOR UPDATE
  TO authenticated
  USING (false);

CREATE POLICY "Restrict delete access to authenticated users"
  ON securities FOR DELETE
  TO authenticated
  USING (false);

-- 2. Volatility History table
ALTER TABLE volatility_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to volatility_history"
  ON volatility_history FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Restrict write access to authenticated users"
  ON volatility_history FOR INSERT
  TO authenticated
  WITH CHECK (false);

CREATE POLICY "Restrict update access to authenticated users"
  ON volatility_history FOR UPDATE
  TO authenticated
  USING (false);

CREATE POLICY "Restrict delete access to authenticated users"
  ON volatility_history FOR DELETE
  TO authenticated
  USING (false);

-- 3. Prices History table
ALTER TABLE prices_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to prices_history"
  ON prices_history FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Restrict write access to authenticated users"
  ON prices_history FOR INSERT
  TO authenticated
  WITH CHECK (false);

CREATE POLICY "Restrict update access to authenticated users"
  ON prices_history FOR UPDATE
  TO authenticated
  USING (false);

CREATE POLICY "Restrict delete access to authenticated users"
  ON prices_history FOR DELETE
  TO authenticated
  USING (false);

-- 4. Options Chain table
ALTER TABLE options_chain ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to options_chain"
  ON options_chain FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Restrict write access to authenticated users"
  ON options_chain FOR INSERT
  TO authenticated
  WITH CHECK (false);

CREATE POLICY "Restrict update access to authenticated users"
  ON options_chain FOR UPDATE
  TO authenticated
  USING (false);

CREATE POLICY "Restrict delete access to authenticated users"
  ON options_chain FOR DELETE
  TO authenticated
  USING (false);

-- 5. SHAP Snapshot table
ALTER TABLE shap_snapshot ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to shap_snapshot"
  ON shap_snapshot FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Restrict write access to authenticated users"
  ON shap_snapshot FOR INSERT
  TO authenticated
  WITH CHECK (false);

CREATE POLICY "Restrict update access to authenticated users"
  ON shap_snapshot FOR UPDATE
  TO authenticated
  USING (false);

CREATE POLICY "Restrict delete access to authenticated users"
  ON shap_snapshot FOR DELETE
  TO authenticated
  USING (false);

-- 6. Event History table (per-security)
ALTER TABLE event_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to event_history"
  ON event_history FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Restrict write access to authenticated users"
  ON event_history FOR INSERT
  TO authenticated
  WITH CHECK (false);

CREATE POLICY "Restrict update access to authenticated users"
  ON event_history FOR UPDATE
  TO authenticated
  USING (false);

CREATE POLICY "Restrict delete access to authenticated users"
  ON event_history FOR DELETE
  TO authenticated
  USING (false);

-- 7. Macro Calendar table (market-wide events)
ALTER TABLE macro_calendar ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to macro_calendar"
  ON macro_calendar FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Restrict write access to authenticated users"
  ON macro_calendar FOR INSERT
  TO authenticated
  WITH CHECK (false);

CREATE POLICY "Restrict update access to authenticated users"
  ON macro_calendar FOR UPDATE
  TO authenticated
  USING (false);

CREATE POLICY "Restrict delete access to authenticated users"
  ON macro_calendar FOR DELETE
  TO authenticated
  USING (false);
